### ISSUE TITLE
Error: Unable to get the 'EASW_ID'.

### ISSUE THREAD

**Issue by lBroth** [futjs/fut-api#8]
I get this error in login

Error: Unable to get the 'EASW_ID'. Unable to login.
    at Request._callback (/var/nodejs/node_modules/fut-api/lib/login.js:205:75)
    at Request.self.callback (/var/nodejs/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/nodejs/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/var/nodejs/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)

Do you have an idea to solve this?

**Comment by lBroth** [comment]
I think the EA sport web app server are down

**Comment by gregbarcza** [comment]
You can use `loginType: mobile` when the web-app is down: https://github.com/futjs/fut-api/blob/master/examples/example.js#L26
I will make a more meaningful error message for this one!

**Comment by CRCameron** [comment]
Are you still unable to login to web app? I can login fine by going to the site. But using the API I just get 'Error: Unable to log in.'

**Comment by lBroth** [comment]
Yes but with mobile login works well.

You can print the response and error in the login callback to get error details.
